# Generated by Django 6.0.2 on 2026-02-14 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('style', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('GK', 'Goalkeeper'), ('OUT', 'Outfielder')], max_length=3)),
                ('vision', models.IntegerField(default=60)),
                ('finishing', models.IntegerField(default=60)),
                ('composure', models.IntegerField(default=60)),
                ('def_awareness', models.IntegerField(default=60)),
                ('short_passing', models.IntegerField(default=60)),
                ('interceptions', models.IntegerField(default=60)),
                ('stamina', models.IntegerField(default=70)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.team')),
            ],
        ),
    ]
