# Generated by Django 6.0.2 on 2026-02-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tactical_mode',
            field=models.CharField(default='STANDARD', max_length=20),
        ),
    ]
