# Generated by Django 6.0.2 on 2026-02-16 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_team_tactical_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='style',
        ),
        migrations.AddField(
            model_name='player',
            name='is_starting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='preferred_zone',
            field=models.CharField(choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('GK', 'GK'), ('DEF', 'DEF'), ('MID', 'MID'), ('FWD', 'FWD')], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='engine.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tactical_mode',
            field=models.CharField(choices=[('Standard', 'Standard'), ('High Press', 'High Press'), ('Park the Bus', 'Park the Bus'), ('Tiki Taka', 'Tiki Taka'), ('Counter Attack', 'Counter Attack')], default='Standard', max_length=50),
        ),
    ]
