# Generated by Django 6.0.2 on 2026-02-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_remove_team_style_player_is_starting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='defense',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='passing',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='shooting',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='speed',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='team',
            name='attack_strength',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='team',
            name='defense_strength',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='composure',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='def_awareness',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='finishing',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='interceptions',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='preferred_zone',
            field=models.CharField(default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='short_passing',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='vision',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='tactical_mode',
            field=models.CharField(default='STANDARD', max_length=20),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(max_length=10)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('stats', models.JSONField(default=dict)),
                ('logs', models.JSONField(default=list)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='engine.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='engine.team')),
            ],
        ),
    ]
