# Generated by Django 6.0.2 on 2026-02-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_player_defense_player_passing_player_shooting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slot_11v11',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='slot_5v5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
