# Generated by Django 6.0.2 on 2026-02-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_player_slot_11v11_player_slot_5v5'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='set_piece_role',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='tactical_instruction',
            field=models.CharField(blank=True, default='Standard', max_length=50),
        ),
    ]
