# Generated by Django 6.0.2 on 2026-02-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_player_set_piece_role_player_tactical_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='preferred_zone',
            field=models.CharField(blank=True, default='Center', max_length=50, null=True),
        ),
    ]
