# Generated by Django 5.1 on 2026-07-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0007_alter_player_preferred_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="dribbling",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="gk_aerials",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="gk_handling",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="gk_reflexes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="heading",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="marking",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="match",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
